name: Build Theos Packages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: ${{ env.THEOS }}

      - name: Build rootless package
        run: |
          make clean
          make package THEOS=$THEOS THEOS_PACKAGE_SCHEME=rootless

      - name: Upload rootless artifact
        uses: actions/upload-artifact@v4
        with:
          name: rootless-deb
          path: packages/*.deb
          if-no-files-found: error

      - name: Build roothide package
        run: |
          make clean
          make package THEOS=$THEOS THEOS_PACKAGE_SCHEME=roothide

      - name: Upload roothide artifact
        uses: actions/upload-artifact@v4
        with:
          name: roothide-deb
          path: packages/*.deb
          if-no-files-found: error
